Fix setup.py numpy header missing
Include numpy header path when trying to cythonize to avoid path missing error "fastdtw/_fastdtw.cpp:465:28: fatal error: numpy/npy_math.h: No such file or directory".